### ISSUE TITLE
[오작동 보고]마우스 클릭 이벤트와 키보드 단축키 이벤트 오작동

### ISSUE THREAD

**Issue by ks2colorworld** [sunghyuk/D3-Skill-Assistant#5]
맥용 D3Helper 정말 반갑습니다. 
오늘 설치해서 한번 사용해 봤는데요. 
오류가 있어서 글 남깁니다.
확인하시고 오류 수정해 주시면 고맙겠습니다. ^^

(테스트 설정 예시)
**4** key : 100 
**left mouse delay** :  5000 

(나타나는 현상)
1. 시작키를 누르면 마우스 왼쪽클릭 작동 없이 0.1초 간격으로 **4** key 약 2-3초간 키보드 이벤트 작동함.
2. 그리고 약 2-3초동안 마우스 왼쪽클릭이 작동하고(화면상으로는 클릭효과나 나타나지 않음) **4** key 매크로는 작동 하지 않음.
3. 그리고 2-3초 후 다시 1번 현상이 반복됨.

(기대했던 예상 작동)
1. key 매크로와 마우스 클릭 이벤트는 작동시 서로 영향을 주지 않아야 함.
2. 시작키를 누름과 동시에 마우스 클릭 이벤트와 key 매크로가 동시에 작동해야 함.
3. 마우스 왼쪽 클릭 이벤트는 종료키를 누르기 전까지 5초에 한번씩 작동함.
4. 4 key 매크로는 종료키를 누르기 전까지 0.1초에 한번씩 작동함.

(추가 요청 기능)
1. 특정 키(예 : space, 4 등등 설정가능)를 누르면 모든 매크로 일시정지함.
2. 1~5번까지 설정된 매크로들을 각각 활성/비활성 설정하고, 작동 될 수 있도록 함. (혹은 설정값이 다르게 설정된 여러 창을 띄워서 사용할 수 있도록 함.)

감사합니다.

**Comment by sunghyuk** [comment]
선 딜레이가 있는 부분은 알고 있던 문제라 수정할 수 있을 것 같습니다. 

마우스 이벤트 후 몇 초간 키 이벤트가 발생하지 않는 건 확인해봐야 할 거 같구요 

추가 요청 1번은 반영할 수 있을 거 같은데 
2번 어떤 상황에서 필요하신건가요? 설정끼리 꼬일 수도 있을 거 같은데요

**Comment by ks2colorworld** [comment]
한번 쓰면서 너무 많은 내용을 적었네요. 
간략하게 오류내용만 쓸껄 욕심이 과했습니다. 

추가요청기능 2번 관련
예로 
F1 - 습격악사용 세팅
F2 - 부정악사용 세팅
F3 - 악몽포격용 세팅
등등 
캐릭 바꿀 때마다 게임밖으로 나가서 설정을 안바꾸고 매크로를 작동시키도록 하기 위함입니다. 
(윈도우용 D3helper의 경우 창을 여러개 띄어 놓고 각각 다르게 설정해서 입맛대로 쓸 수 있지만, 항상 다시 설정파일을 로드해야 합니다. 이 어플은 처음부터 설정을 1-5까지 되어 있어서 좋다고 생각했습니다. ^^)

*메모기능 추가해 주시는 것도 고려해 주세요. 
-어떤 세팅을 위한 설정인지 바로 알 수 있도록.

**Comment by sunghyuk** [comment]
- [x] 선딜레이 제거 
- [x] timer 오류 수정

**Comment by ks2colorworld** [comment]
의견 반영해 주셔서 감사합니다. ^^

**Comment by sunghyuk** [comment]
설정 기능 개선은 시간이 좀 걸릴 거 같아서 이슈 분리하고 버그 수정부터 처리할게요

**Comment by sunghyuk** [comment]
1.2 수정 배포.

**Comment by ks2colorworld** [comment]
1.2 버전 사용해 보니 이전의 오작동 없이 잘 작동합니다. 
감사합니다. ^^

**Comment by glorykim99** [comment]
감사합니다 잘사용하고 있습니다 !! 윈 헬퍼에 있는 특수키 설정 기능을 부탁합니다~
