### ISSUE TITLE
맥용 앱은 어떻게 실행파일로 뽑나요?

### ISSUE THREAD

**Issue by qwertystar89** [sunghyuk/D3-Skill-Assistant#9]
맥용 앱은 어떻게 실행파일로 뽑나요?

다행이 iOS쪽 개발하다보니; xcode는 설치되어있어서 매번 빌드해 서쓰고있...

**Comment by sunghyuk** [comment]
iOS랑 비슷합니다. Archive 메뉴 이용하시면 되요
